agent_name = "digihire-agent-01"
image = "your_username/digihire-agent-01:0.1"
secret_set = "digihire-agent-01-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
# image_credentials = "your_image_pull_secret"

[scaling]
	min_agents = 1